### PR TITLE
setting bookmarks

### PR DESCRIPTION
**Pull request by antoniatandler**
the yogi can now click the heart icons to set the pose as favorite 

(they will be displayed on a extra page in progress)

### CODE REVIEW

**Comment by TmWgnr** [comment]
looks good to me, everything is working. 
in my opinion the filled and the empty heart should be same size but thats just matter of taste :)

**Comment by antoniatandler** [comment]
> looks good to me, everything is working. in my opinion the filled and the empty heart should be same size but thats just matter of taste :)

can you show me a screenshot of what you mean please? because in my browser they are same sized 😳

Bildschirmfoto 2023-06-19 um 15 23 39

**Comment by TmWgnr** [comment]
what kind of browser do you use? I browse with chrome 🏄🏻‍♂️

Screenshot 2023-06-19 at 15 29 22

**Comment by antoniatandler** [comment]
> what kind of browser do you use? I browse with chrome 🏄🏻‍♂️

I browse with firefox developer edition 🤠

**Pull request merged**
